export const API_CONTROLLER_NEWUSER_URL = process.env.NEXT_PUBLIC_API_NEWUSER_URL;
export const API_CONTROLLER_USERCONTROLLER_URL = process.env.NEXT_PUBLIC_API_GETALLUSERS_URL;
export const API_CONTROLLER_LOGOUT_URL = process.env.NEXT_PUBLIC_API_LOGOUT_URL;
export const API_CONTROLLER_LOGIN_URL = process.env.NEXT_PUBLIC_API_LOGIN_URL;
export const API_CONTROLLER_UPDATEUSER_URL = process.env.NEXT_PUBLIC_API_UPDATEUSER_URL;
export const API_CONTROLLER_DELETEUSER_URL = process.env.NEXT_PUBLIC_API_DELETEUSER_URL;
